# Generated by Django 6.0.6 on 2026-06-11 18:47

import django.db.models.functions.text
from django.db import migrations, models


def normalize_existing_emails(apps, schema_editor):
    User = apps.get_model("users", "User")
    users = list(User.objects.all().order_by("created_at", "id"))
    normalized_emails = {}

    for user in users:
        normalized_email = user.email.strip().lower()
        existing_user_id = normalized_emails.get(normalized_email)
        if existing_user_id is not None:
            raise RuntimeError(
                "Cannot add case-insensitive email constraint: "
                f"users {existing_user_id} and {user.id} have duplicate emails."
            )
        normalized_emails[normalized_email] = user.id
        user.email = normalized_email

    User.objects.bulk_update(users, ["email"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            normalize_existing_emails,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_user_email_ci",
            ),
        ),
    ]
